# Upload package to PyPI

name: Publish PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pypaperless
    outputs:
      version: ${{ steps.vars.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
    - name: Get tag
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build tomli tomli-w
    - name: Set Python project version from tag
      shell: python
      run: |-
        import tomli
        import tomli_w

        with open("pyproject.toml", "rb") as f:
          pyproject = tomli.load(f)

        pyproject["project"]["version"] = "${{ steps.vars.outputs.tag }}"

        with open("pyproject.toml", "wb") as f:
          tomli_w.dump(pyproject, f)
    - name: Build package
      run: python -m build
    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
